CREATE table medicines
(
    mid NUMBER ,
    mname varchar(30) not null,
    mpower int not null,
    mcategory int not null,
    mandate DATE not null,
    expdate DATE not null,
    stock int not null,
    mcost float not null,
    mdesc varchar(100),
    primary key(mid),
    CONSTRAINT c3 foreign key(mcategory) references category(cid)
);

CREATE TABLE purchase
(
    purchase_id int,
    order_id int not null,
    mid int not null,
    quantity int not null,
    dop timestamp not null,
    primary key(purchase_id),
    CONSTRAINT C1 foreign key(mid) references medicines(mid) ON DELETE CASCADE,
    CONSTRAINT C2 foreign key(order_id) references orders(order_id) ON DELETE CASCADE
);



CREATE SEQUENCE seq1
start with 1
increment by 1;

CREATE OR REPLACE TRIGGER mid
BEFORE INSERT ON medicines
FOR EACH ROW

BEGIN
    SELECT seq1.nextval
    INTO :new.mid
    FROM dual;

END;



CREATE SEQUENCE seq2
start with 1
increment by 1;


CREATE OR REPLACE TRIGGER pid
BEFORE INSERT ON purchase
FOR EACH ROW

BEGIN
    SELECT seq2.nextval
    INTO :new.purchase_id
    FROM dual;

END;

CREATE table users
(
    id NUMBER GENERATED by default on null as IDENTITY,
    name varchar(25) not null,
    username varchar(25) not null,
    password varchar(100) not null,
    phone_num varchar(10) not null,
    address varchar(30) not null,
    email varchar(100) not null,
    date_created timestamp ,
    user_level int default 0,
    primary key(id)
);
CREATE table category
(
    cid  NUMBER GENERATED by default on null as IDENTITY,
    cname varchar(20) not null,
    primary key(cid)
);


CREATE TABLE orders
(
    order_id NUMBER GENERATED by default on null as IDENTITY,
    order_by int not null,
    total_cost int not null,
    primary key(order_id),
    foreign key(order_by) references users(id)
);




